experiment_name: "test_lvfa"
simulations: 1
episodes: 1000
save_freq: 100
save_q: True
save_rewards: True
save_lidar: True
Environment:
  map: "map2"
  ActionSpace:
    space_type: 1
    read_sensor: True
  StateSpace:
    space_type: 1
    sensor_model: 0
    reducer: "features"
    Features:
      features_type: "tile"
      levels: 4
      size: 3
      crop: 120
      clip_range: 2.0
    # reducer: "discretize"
    # Discretizer:
    #   discretize_type: "grid"
    #   levels: 4
    #   size: 3
    #   crop: 120
    #   clip_range: 2.0
RLAgent:
  algorithm: 'sarsa'
  lvfa : True
  policy: "softmax"
  temperature : 0.1
  # policy: "eps_greedy"
  # epsilon: 0.05
  feature_size: 74
  alpha: 0.1
  gamma: 0.9
  eligibility: True
